include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = HelloWorld

HelloWorld_OBJC_FILES = main.m MyController.m

HelloWorld_MAIN_MODEL_FILE = helloworld.gorm

HelloWorld_RESOURCE_FILES = helloworld.gorm

include $(GNUSTEP_MAKEFILES)/application.make

